# SOURCE MACHINE-SPECIFIC CONFIGURATION
source = ~/.config/hypr/local.conf

splash = false

wallpaper {
    monitor = $primary_monitor
    path = $wallpaper_primary
}

wallpaper {
    monitor = $secondary_monitor
    path = $wallpaper_secondary
}
